name: Update Charts

on:    
    # Automatically run every 12 hours.
  schedule:
    - cron: '0 */12 * * *'

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_charts:
    name: Update charts
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Notebook Script
      run: |
        jupyter nbconvert --to script notebook.ipynb
        python notebook.py
    
    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add Figures/
        git commit -m "`date` Updated figures with GitHub Actions"
        git push origin main
